export type OpenIdentityErrorCode =
  | "INVALID_SEQUENCE"
  | "INVALID_CONTROLLER_THRESHOLD"
  | "DUPLICATE_VERIFICATION_METHOD"
  | "UNSUPPORTED_ALGORITHM"
  | "UNSUPPORTED_PROTOCOL_FEATURE"
  | "UNSUPPORTED_OPERATION"
  | "INVALID_ASSERTION_THRESHOLD"
  | "STATE_VERSION_DOWNGRADE"
  | "INVALID_PREVIOUS_STATE_HASH"
  | "CONTROLLER_THRESHOLD_NOT_SATISFIED"
  | "DUPLICATE_PROOF"
  | "INVALID_SIGNATURE"
  | "UNAUTHORIZED_VERIFICATION_METHOD"
  | "MISSING_PROOF_OF_POSSESSION"
  | "INVALID_PROOF_OF_POSSESSION"
  | "RECOVERY_NOT_CONFIGURED"
  | "INVALID_RECOVERY_POLICY"
  | "INVALID_RECOVERY_THRESHOLD"
  | "RECOVERY_THRESHOLD_NOT_SATISFIED"
  | "DUPLICATE_RECOVERY_PROOF"
  | "UNAUTHORIZED_RECOVERY_METHOD"
  | "INVALID_RECOVERY_SIGNATURE"
  | "INVALID_RECOVERY_COMMITMENT";

export class OpenIdentityValidationError extends Error {
  constructor(readonly code: OpenIdentityErrorCode) {
    super(code);
    this.name = "OpenIdentityValidationError";
  }
}
